import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NewsScroller } from "../components/NewsScrolling";
import { carouselItems, newsItems } from "./page";
import { ContinuousCarousel } from "../components/AnimatedCarousel";
import QueryProvider from "./providers/QueryProvider";
import ToastProvider from "./providers/ToastProvider";
import Sidebar from "../components/Sidebar";
import LayoutWrapper from "./LayoutWrapper";
import FooterComponent from "../components/FooterComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-serif flex flex-col min-h-screen">
       
       
    
 
 
    <main className="grow bg-white p-0">
     
    <LayoutWrapper> <QueryProvider>
          {children}
          <ToastProvider />
        </QueryProvider>
        </LayoutWrapper>
      
      </main>

   




  
      </body>
    </html>
  );
}

